---
functional:
  - Пользователи должны иметь возможность соревноваться друг с другом в решении задач.
  - Система должна поддерживать различные языки программирования для решения задач (Clojure, Cpp, Csharp, Dart, Elixir, Go, Haskell, JaVa, JavaScript, Kotlin, PHP, Python, Ruby, Rust, Typescript).
  - Пользователи должны видеть код друг друга в реальном времени во время соревнований.
  - Должна быть возможность играть с живым соперником или с ботом.
  - Должны отображаться рейтинги пользователей на основе их результатов.
  - Должна быть возможность создавать турниры.
  - Должна быть возможность общаться в чате с пользователями сайта.
  - Противники должны иметь возможность общения во время боя.
  - Должна быть возможность сдаться.

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть быть оптимизирован на мобильные устройства.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров(Chrome, Edge, Firerox, Yandex, Safary).
  - Сайт должен способен обрабатывать большое количество трафика пользователей.

implicit:
  - Должен настраиваться профиль.
  - Система должна быть интуитивно понятной и легкой в использовании.
  - Должны учитываться отзывы и предложения пользователей для улучшения функциональности.
  - Должна быть форма обратной связи.
  - Должна предоставляться своевременные уведомления о результатах соревнований и обновлениях.
  - Система должна быть стабильной не зависать и не выдавать ошибки.
  - Должна быть возможность легко восстановить доступ к аккаунту в случае потери пароля или других проблем с входом.
  - Пользователи хотят видеть активное сообщество, включая форумы или чаты для обсуждения задач и обмена опытом.
